# Generated by Django 4.0.4 on 2022-05-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std',
            field=models.IntegerField(),
        ),
    ]
