# Generated by Django 4.0.4 on 2022-06-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('teacher_age', models.CharField(max_length=200)),
                ('teacher_email', models.CharField(max_length=200)),
            ],
        ),
    ]
